### ISSUE TITLE
[Feature Request] Add defaultArbInputFolder to the Extension Settings parameters

### ISSUE THREAD

**Issue by TheFabbiusCorp** [innwin/vsce-i18n-arb-editor#4]
I am loving this extension! It would be great to have a default ARB file path the extension would look into when it is opened from the Command Palette. At the moment, you can only make it work by right-clicking the folder from the Project view, but I think it would be handy to set a default file path for input ARB files, especially if projects use similar architectures.

What do you think?

**Comment by DionJChapman** [comment]
Try this version: https://marketplace.visualstudio.com/items?itemName=NativeBit.i18n-l10n-editor

**Comment by TheFabbiusCorp** [comment]
Cool @DionJChapman! However, adding the folder to "i18n-l10n-editor.supportedFolders" doesn't seem to work...

**Comment by DionJChapman** [comment]
> Cool @DionJChapman! However, adding the folder to "i18n-l10n-editor.supportedFolders" doesn't seem to work...

Please send me the settings and your folder. have you set up an l10n.yaml file with

`arb-dir: directory

template-arb-file:`

**Comment by TheFabbiusCorp** [comment]
I don't have a l10n.yaml file but I set in my pubspec.yaml these lines:

```yaml
flutter_intl:
  enabled: true
  main_locale: en_US
  arb_dir: lib/design_system/localization/translations
  output_dir: lib/design_system/localization/generated
```
